#!/usr/bin/env node
// The evidence binding (D97), asked of the rows already recorded: for every measurement the import pipeline wrote,
// whether the value the table holds today is a number its evidence line prints, whole, and whether a number the line
// prints once was given two roles (a value and its test temperature; an anneal and a test temperature).
//
// The apply guard asks this of every row entering now. Rows applied before 2026-09-28 were accepted by a page-wide
// test that "52" answered for 5, so they are read here, not refused after the fact. A row listed is a question for a
// person with the page open, not a finding that the value is wrong: a later migration may have corrected the value
// against the page (its Notes say so), and a layout the reader could not bind may be right.
//
//   npm run audit:witness            writes docs/audits/2026-09-27-v2.1-review/WITNESS-BINDING.md

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readCsv } from '../../build/src/csv.js';
import { PROPOSALS } from '../ingest/archive.mjs';
import { valueInEvidence, countInEvidence } from '../lib/pdf-text.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '../..');
const out = join(root, 'docs/audits/2026-09-27-v2.1-review/WITNESS-BINDING.md');
const isNumber = (v) => v != null && /^-?\d/.test(String(v));
const BOUND = ['Raw numeric', 'Raw uncertainty ±', 'Raw upper bound'];
const ROLES = [...BOUND, 'Anneal °C', 'Anneal h', 'Test temperature °C'];

const measurements = readCsv(join(root, 'data/tables/measurements.csv')).records.map((r) => r.values)
  .filter((m) => m['Data status'] !== 'Retired duplicate record');
// A row is known by its source, its locator and what it measured under which conditions: one locator may name two
// tables' rows of one property (dry and conditioned, as printed and annealed), which are two measurements.
const KEY = ['SourceID', 'Locator', 'Property', 'Direction', 'Moisture state', 'Post-processing state', 'Notch', 'Test load MPa'];
const keyOf = (row) => KEY.map((k) => row[k] ?? '').join('\u0000');
const byKey = new Map();
for (const m of measurements) byKey.set(keyOf(m), [...(byKey.get(keyOf(m)) ?? []), m]);

// Each recorded row, with the evidence line of the proposal row that wrote it: where one key holds several, the
// proposal row whose value the table still holds.
const evidence = new Map();
const dir = join(root, PROPOSALS);
for (const batch of readdirSync(dir).sort()) {
  for (const f of readdirSync(join(dir, batch)).filter((x) => x.endsWith('.json')).sort()) {
    const p = JSON.parse(readFileSync(join(dir, batch, f), 'utf8'));
    for (const row of p.measurements ?? []) {
      if (row.review?.status !== 'accepted' || !row.row) continue;
      const rows = byKey.get(keyOf(row.row));
      if (!rows) continue;
      const m = rows.find((x) => x['Raw numeric'] === row.row['Raw numeric']) ?? (rows.length === 1 ? rows[0] : null);
      if (m && !evidence.has(m.MeasurementID)) evidence.set(m.MeasurementID, { m, batch, line: row.evidence?.text ?? null, visual: row.review?.visual ?? null });
    }
  }
}

const findings = [];
let bound = 0, visual = 0;
for (const e of evidence.values()) {
  const { m } = e;
  if (e.visual) { visual++; continue; }
  const problems = [];
  for (const field of BOUND) if (isNumber(m[field]) && !valueInEvidence(e.line, m[field])) problems.push(`${field} ${m[field]} is not a number the line prints`);
  const claims = new Map();
  for (const field of ROLES) if (isNumber(m[field])) claims.set(String(Number(m[field])), [...(claims.get(String(Number(m[field]))) ?? []), field]);
  for (const [value, fields] of claims) {
    const n = countInEvidence(e.line, value);
    if (fields.length > 1 && n > 0 && n < fields.length) problems.push(`${value} is printed ${n === 1 ? 'once' : `${n} times`} and is ${fields.join(' and ')}`);
  }
  if (problems.length) findings.push({ m, e, problems });
  else bound++;
}
findings.sort((a, b) => a.m.MeasurementID.localeCompare(b.m.MeasurementID, 'en', { numeric: true }));

const cell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\s+/g, ' ');
const lines = [
  '# The evidence binding, asked of the rows already recorded',
  '',
  '<!-- Generated by npm run audit:witness (scripts/audit/witness-binding.mjs). Do not edit by hand. -->',
  '',
  `The measurements the import pipeline wrote, ${evidence.size} of them, each read against the evidence line its proposal`,
  'carried (D97): is the value the table holds today a number that line prints, whole, and does a number the line prints',
  `once have one role? ${bound} are bound; ${visual} were read by a person on the page image and are not re-asked;`,
  `${findings.length} are listed below for a person with the page open. A row here is a question, not a verdict: a later`,
  'migration may have corrected the value against the page (its Notes say so), and a layout the reader could not bind',
  'may still be right.',
  '',
  'Corrected: the row\'s Notes record a correction against the source since it was applied, which is itself a re-read.',
  '',
  '| Measurement | Grade | Property | Value | Batch | Evidence line | What does not bind | Corrected |',
  '|---|---|---|---|---|---|---|---|',
  ...findings.map(({ m, e, problems }) => `| ${m.MeasurementID} | ${m.GradeID} | ${cell(m.Property)} | ${cell(m['Raw value'])} | ${e.batch} | ${cell(e.line)} | ${cell(problems.join('; '))} | ${/Corrected \d{4}-\d{2}-\d{2}/.test(m.Notes ?? '') ? 'yes' : ''} |`),
  '',
];
writeFileSync(out, lines.join('\n'));
console.log(`audit:witness: ${evidence.size} recorded rows, ${bound} bound, ${visual} read on the page image, ${findings.length} listed in ${out.replace(`${root}/`, '')}`);
