#!/usr/bin/env node
// Generate docs/RULES.md from the rule catalogue (build/src/rules.js).
//   npm run docs:rules            rewrite the file
//   npm run docs:rules -- --check exit 1 if it is out of date (run by npm run verify)
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { RULES } from '../build/src/rules.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const path = join(root, 'docs/RULES.md');
const esc = (s) => s.replace(/\|/g, '\\|');
const L = ['# Rules', '', '<!-- Generated by npm run docs:rules from build/src/rules.js. Do not edit by hand. -->', '',
  'Every check the schema gate, the build, the audit, the contract and the lint can raise, by code. An error stops the',
  'build; a warning is reported; a lint finding stops `npm run verify` until it is fixed or accepted with a reason in',
  '`data/review/accepted-findings.csv`. Messages always name the record; the code says which rule, and this page says',
  'what it means and how to fix it.', ''];
const areas = [...new Set(Object.values(RULES).map((r) => r.area))];
for (const area of areas) {
  L.push(`## ${area[0].toUpperCase()}${area.slice(1)}`, '', '| Code | Level | Means | Fix |', '|---|---|---|---|');
  for (const [code, r] of Object.entries(RULES).filter(([, r]) => r.area === area)) L.push(`| \`${code}\` | ${r.level} | ${esc(r.meaning)} | ${esc(r.fix)} |`);
  L.push('');
}
const text = L.join('\n');
if (process.argv.includes('--check')) {
  if (!existsSync(path) || readFileSync(path, 'utf8') !== text) { console.error('docs/RULES.md is out of date; run npm run docs:rules'); process.exit(1); }
  console.log('docs/RULES.md is current');
} else {
  writeFileSync(path, text);
  console.log(`docs/RULES.md: ${Object.keys(RULES).length} rules`);
}
